#############################################################################
# Makefile for building: calcpp
# Generated by qmake (2.01a) (Qt 4.8.6) on: dom mag 18 10:28:52 2014
# Project:  calcpp.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile calcpp.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -march=i686 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -march=i686 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = key.cxx \
		keyPad.cxx \
		main.cpp \
		mainWindow.cxx \
		mathEntity.cxx \
		mathNumber.cxx \
		mathOperator.cxx \
		mathParser.cxx moc_key.cpp \
		moc_keyPad.cpp \
		moc_mainWindow.cpp
OBJECTS       = key.o \
		keyPad.o \
		main.o \
		mainWindow.o \
		mathEntity.o \
		mathNumber.o \
		mathOperator.o \
		mathParser.o \
		moc_key.o \
		moc_keyPad.o \
		moc_mainWindow.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		calcpp.pro
QMAKE_TARGET  = calcpp
DESTDIR       = 
TARGET        = calcpp

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: calcpp.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile calcpp.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile calcpp.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/calcpp1.0.0 || $(MKDIR) .tmp/calcpp1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/calcpp1.0.0/ && $(COPY_FILE) --parents key.hpp keyPad.hpp mainWindow.hpp mathEntity.hpp mathNumber.hpp mathOperator.hpp mathParser.hpp .tmp/calcpp1.0.0/ && $(COPY_FILE) --parents key.cxx keyPad.cxx main.cpp mainWindow.cxx mathEntity.cxx mathNumber.cxx mathOperator.cxx mathParser.cxx .tmp/calcpp1.0.0/ && (cd `dirname .tmp/calcpp1.0.0` && $(TAR) calcpp1.0.0.tar calcpp1.0.0 && $(COMPRESS) calcpp1.0.0.tar) && $(MOVE) `dirname .tmp/calcpp1.0.0`/calcpp1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/calcpp1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_key.cpp moc_keyPad.cpp moc_mainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_key.cpp moc_keyPad.cpp moc_mainWindow.cpp
moc_key.cpp: key.hpp
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) key.hpp -o moc_key.cpp

moc_keyPad.cpp: key.hpp \
		mathParser.hpp \
		mathEntity.hpp \
		mathOperator.hpp \
		mathNumber.hpp \
		keyPad.hpp
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) keyPad.hpp -o moc_keyPad.cpp

moc_mainWindow.cpp: mainWindow.hpp
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) mainWindow.hpp -o moc_mainWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

key.o: key.cxx key.hpp \
		keyPad.hpp \
		mathParser.hpp \
		mathEntity.hpp \
		mathOperator.hpp \
		mathNumber.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o key.o key.cxx

keyPad.o: keyPad.cxx keyPad.hpp \
		key.hpp \
		mathParser.hpp \
		mathEntity.hpp \
		mathOperator.hpp \
		mathNumber.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o keyPad.o keyPad.cxx

main.o: main.cpp mainWindow.hpp \
		keyPad.hpp \
		key.hpp \
		mathParser.hpp \
		mathEntity.hpp \
		mathOperator.hpp \
		mathNumber.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainWindow.o: mainWindow.cxx mainWindow.hpp \
		keyPad.hpp \
		key.hpp \
		mathParser.hpp \
		mathEntity.hpp \
		mathOperator.hpp \
		mathNumber.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainWindow.o mainWindow.cxx

mathEntity.o: mathEntity.cxx mathEntity.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mathEntity.o mathEntity.cxx

mathNumber.o: mathNumber.cxx mathNumber.hpp \
		mathEntity.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mathNumber.o mathNumber.cxx

mathOperator.o: mathOperator.cxx mathOperator.hpp \
		mathEntity.hpp \
		mathNumber.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mathOperator.o mathOperator.cxx

mathParser.o: mathParser.cxx mathParser.hpp \
		mathEntity.hpp \
		mathOperator.hpp \
		mathNumber.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mathParser.o mathParser.cxx

moc_key.o: moc_key.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_key.o moc_key.cpp

moc_keyPad.o: moc_keyPad.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_keyPad.o moc_keyPad.cpp

moc_mainWindow.o: moc_mainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainWindow.o moc_mainWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

